version: '3.8'

services:
  web:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./sql_app.db
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: worker
    command: python worker/worker.py
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672   
    depends_on:
      - rabbitmq

  tests:
    build: .
    container_name: test_runner
    command: python -m pytest
    environment:
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
